// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzsflibcvrisxjlzuxjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56c2ZsaWJjdnJpc3hqbHp1eGpuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMTczMTksImV4cCI6MjA1NzY5MzMxOX0.Xfrp1zxJUFy2NEg_ZJJkf6aHj6v94_JHQ26BuZNsMis";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);